### ISSUE TITLE
In memory panic stackshot succeeded

### ISSUE THREAD

**Issue by ArchyCho** [cstrouse/Dell-T3610-Hackintosh#5]
Hello 
I have a DELL Precision T5610 ( I think it should similar with T3610 ) , 
I have installed Ubuntu and use SSDTime to exported all SSDT files with no luck.
I tried to install 10.15.7 , 11.6 with no success.

I use my own configuration and try this OC / Clover installation , getting same result 
** In memory panic stackshot succeeded ** Bytes Traced 14695 (Uncompressed 66768)

Any ideas ?

E5-2697v2 x2
16G DDR3x8 = 128G
1T Micron SSD with AHCI

Attached Panic log for clover :
mp_kdp_enter() can't get x86_topo_lock! Debugging anyway! #YOLO
panic(cpu 26 caller 0xffffff80034449ea): Kernel trap at 0xffffff7f873e9c7b, type 13=general protection, registers:
CR0: 0x000000008001003b, CR2: 0x0000000105c39000, CR3: 0x0000000018c94000, CR4: 0x00000000001626e0
RAX: 0x61dfc1db8a8b00db, RBX: 0xffffff81083a9900, RCX: 0x000000000000001a, RDX: 0x0000000000000000
RSP: 0xffffff8e16c3be80, RBP: 0xffffff8e16c3beb0, RSI: 0xffffff810a8415c0, RDI: 0x0000000000000002
R8:  0x0000000000000001, R9:  0x0000000000000000, R10: 0x0000000000000000, R11: 0x0000000000000000
R12: 0x0000000000000138, R13: 0x0000000000000000, R14: 0xffffff8003e55648, R15: 0xffffff8106fdf000
RFL: 0x0000000000010093, RIP: 0xffffff7f873e9c7b, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000105c39000, Error code: 0x0000000000000000, Fault CPU: 0x1a, PL: 2, VF: 0

Backtrace (CPU 26), Frame : Return Address
0xffffff800315e220 : 0xffffff800331868d 
0xffffff800315e270 : 0xffffff8003452ab5 
0xffffff800315e2b0 : 0xffffff800344463e 
0xffffff800315e300 : 0xffffff80032bea40 
0xffffff800315e320 : 0xffffff8003317d57 
0xffffff800315e420 : 0xffffff8003318147 
0xffffff800315e470 : 0xffffff8003abf2bc 
0xffffff800315e4e0 : 0xffffff80034449ea 
0xffffff800315e660 : 0xffffff80034446e8 
0xffffff800315e6b0 : 0xffffff80032bea40 
0xffffff800315e6d0 : 0xffffff7f873e9c7b 
0xffffff8e16c3beb0 : 0xffffff800344dae3 
0xffffff8e16c3bf20 : 0xffffff800344d7a2 
0xffffff8e16c3bf60 : 0xffffff800344c6a3 
0xffffff8e16c3bf80 : 0xffffff8003443e3b 
0xffffff8e16c3bfd0 : 0xffffff80032bebed 
0xffffff8e30903f40 : 0xffffff800333d7e7 
0xffffff8e30903f80 : 0xffffff800333d9a8 
0xffffff8e30903fa0 : 0xffffff80032be13e 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleIntelMCEReporter(115.0)[62FC776D-75D3-365A-A6F2-A5CB65314F5E]com.apple.0xffffff7f873e4000-com.apple.driver.0xffffff7f873f6fff
            dependency: com.apple.iokit.IOACPIFamily(1.4)[2956198D-24F2-3790-A9B2-1EAB9434B906]com.apple.0xffffff7f83d09000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[2F37AE58-E6B9-3B18-9092-3B80D34C334B]com.apple.0xffffff7f83d12000

BSD process name corresponding to current thread: kernel_task
Boot args: npci=0x2000 dart=0 -v alcid=3 root-dmg=file:///Install%20macOS%20Catalina.app/Contents/SharedSupport/BaseSystem.dmg

Mac OS version:
19H15

Kernel version:
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
Kernel UUID: 9B5A7191-5B84-3990-8710-D9BD9273A8E5
Kernel slide:     0x0000000003000000
Kernel text base: 0xffffff8003200000
__HIB  text base: 0xffffff8003100000
System model name: MacPro6,1 (Mac-F60DEB81FF30ACF6)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization

System uptime in nanoseconds: 88422085013
last loaded kext at 86878742090: com.apple.driver.AppleIntelMCEReporter	115 (addr 0xffffff7f873e4000, size 77824)
last unloaded kext at 63831699290: com.apple.driver.AppleXsanScheme	3 (addr 0xffffff7f86941000, size 40960)
loaded kexts:

**Comment by ArchyCho** [comment]
Fixed with downgraded a BIOS :) finally.

**Comment by Vedovatod** [comment]
Hi,
Same Dell machine, same CPUs 
Followed your suggestion to downgrade bios from A19 to A06 but no luck. Could you share your EFI folder? Thanks

**Comment by cosmiccowboy68** [comment]
Experienced hackintosher stumped for months trying, But Finally, I have found a way to install Monterey, Ventura and Soboma onto a  DELL Precision T3610. Which I thought was impossible due to its bios and lack of certain functions such as TSC_sync.
I found this page for a x79 MB.

https://github.com/acidanthera/bugtracker/issues/2163 

and used the EFI found here as a base 

https://github.com/acidanthera/bugtracker/files/10074725/ESP.Dump.zip 

If there is any interest I can give out more details.

**Comment by cstrouse** [comment]
@cosmiccowboy68 I no longer have this hardware but if you'd like to collab and test I'd be happy to update this repo with your help.

**Comment by cosmiccowboy68** [comment]
@cstrouse No problem, I will update you once I have a completed EFI that can be uploaded as I still don't understand how it worked using a patched DSDT from a Chinese MoBo on my Dell T3610 to be able to update from Big Sur!!
